// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	rest "github.com/J-Obog/paidoff/rest"
	mock "github.com/stretchr/testify/mock"
)

// RouteHandler is an autogenerated mock type for the RouteHandler type
type RouteHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RouteHandler) Execute(_a0 *rest.Request) *rest.Response {
	ret := _m.Called(_a0)

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(*rest.Request) *rest.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	return r0
}

// NewRouteHandler creates a new instance of RouteHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouteHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RouteHandler {
	mock := &RouteHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
