// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	data "github.com/J-Obog/paidoff/data"
	mock "github.com/stretchr/testify/mock"
)

// TransactionStore is an autogenerated mock type for the TransactionStore type
type TransactionStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id, accountId
func (_m *TransactionStore) Delete(id string, accountId string) (bool, error) {
	ret := _m.Called(id, accountId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(id, accountId)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(id, accountId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAll provides a mock function with given fields:
func (_m *TransactionStore) DeleteAll() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id, accountId
func (_m *TransactionStore) Get(id string, accountId string) (*data.Transaction, error) {
	ret := _m.Called(id, accountId)

	var r0 *data.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*data.Transaction, error)); ok {
		return rf(id, accountId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *data.Transaction); ok {
		r0 = rf(id, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBy provides a mock function with given fields: accountId, filter
func (_m *TransactionStore) GetBy(accountId string, filter data.TransactionFilter) ([]data.Transaction, error) {
	ret := _m.Called(accountId, filter)

	var r0 []data.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, data.TransactionFilter) ([]data.Transaction, error)); ok {
		return rf(accountId, filter)
	}
	if rf, ok := ret.Get(0).(func(string, data.TransactionFilter) []data.Transaction); ok {
		r0 = rf(accountId, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, data.TransactionFilter) error); ok {
		r1 = rf(accountId, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPeriodCategory provides a mock function with given fields: accountId, categoryId, month, year
func (_m *TransactionStore) GetByPeriodCategory(accountId string, categoryId string, month int, year int) ([]data.Transaction, error) {
	ret := _m.Called(accountId, categoryId, month, year)

	var r0 []data.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int, int) ([]data.Transaction, error)); ok {
		return rf(accountId, categoryId, month, year)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, int) []data.Transaction); ok {
		r0 = rf(accountId, categoryId, month, year)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, int) error); ok {
		r1 = rf(accountId, categoryId, month, year)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: transaction
func (_m *TransactionStore) Insert(transaction data.Transaction) error {
	ret := _m.Called(transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(data.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: id, accountId, update, timestamp
func (_m *TransactionStore) Update(id string, accountId string, update data.TransactionUpdate, timestamp int64) (bool, error) {
	ret := _m.Called(id, accountId, update, timestamp)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, data.TransactionUpdate, int64) (bool, error)); ok {
		return rf(id, accountId, update, timestamp)
	}
	if rf, ok := ret.Get(0).(func(string, string, data.TransactionUpdate, int64) bool); ok {
		r0 = rf(id, accountId, update, timestamp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, data.TransactionUpdate, int64) error); ok {
		r1 = rf(id, accountId, update, timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionStore creates a new instance of TransactionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionStore {
	mock := &TransactionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
