// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UIDProvider is an autogenerated mock type for the UIDProvider type
type UIDProvider struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *UIDProvider) GetId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewUIDProvider creates a new instance of UIDProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUIDProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UIDProvider {
	mock := &UIDProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
