// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UuidProvider is an autogenerated mock type for the UuidProvider type
type UuidProvider struct {
	mock.Mock
}

// GetUuid provides a mock function with given fields:
func (_m *UuidProvider) GetUuid() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewUuidProvider creates a new instance of UuidProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUuidProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UuidProvider {
	mock := &UuidProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
